name: 'Zen & Anarchy'
favicon: null
layout_spectrum: 0.61563
typography_spectrum: 0.5788531
title: 'Zen & Anarchy'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-71743318-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#150f13'
    - '#403531'
    - '#bbc5ad'
    - '#808068'
  brandStrength: 0.4375
  lightness: 0.25
  saturation: 1
  rhythmicContrast: 1
purpose: []
